### ISSUE TITLE
web sekolah

### ISSUE THREAD

**Issue by tyoerror** [romadebrian/WEB-Sekolah#8]
di hak akses guru tidak ada input untuk masukan  nilai atau crudnya tidak ada hanya sekedar tampil saja

**Comment by romadebrian** [comment]
bisa kok gan input nilai, edit, bahkan hapus
hanya saja saya jadikan 1 form karena lagiitu sudah dead line sampai tidak tidur full day wkwkkwk

**Comment by tyoerror** [comment]
Wkwkkk gue ngerti banget tuh rasanya gan .. btw kalo boleh . Bisa tolong di kirim sourcode lengkapnya ke email saya gan. tyo.ebeth@yahoo.com. Thx gan

**Comment by romadebrian** [comment]
udah ea

**Comment by romadebrian** [comment]
kuy lah ngembangin juga :v

**Comment by hardiferio** [comment]
Mas.. bisa kirim source code lengkap ke emailku hardiferio@gmail.com
Makasih..

**Comment by romadebrian** [comment]
yang di sini juga sudah lengkap mas
hanya saja belum sempat saya kembangin lagi
