### ISSUE TITLE
Warning: session_start(): Cannot send session cache limiter - headers already sent 

### ISSUE THREAD

**Issue by romadebrian** [romadebrian/WEB-Sekolah#9]
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /storage/ssd2/019/12549019/public_html/index.php:28) in /storage/ssd2/019/12549019/public_html/napigasi.php on line 23

**Comment by romadebrian** [comment]
cara mengatasi ini adalah dengan cara menaruh 
<?php session_start(); ?>

di setiap page sebelum tag <html>

https://kursuswebprogramming.com/cara-mengatasi-session_start-cannot-send-session-cache-limiter-headers-already-sent/

**Comment by romadebrian** [comment]
gw nya males njirrr benerin semua wkwkkw

**Comment by romadebrian** [comment]
kali aja ada yang mau nyoba benerin soalnya ini muncul ketika di hosting dan kalo di web cms sekolah github ini gw hide biar gak kelihatan errornya wkwkkw

**Comment by RADEN-ies** [comment]
mas untuk database nya kok nggak bisa di import ya mas

**Comment by romadebrian** [comment]
> 
> 
> mas untuk database nya kok nggak bisa di import ya mas
 
Coba impor textnya aja (SQL Query)
https://github.com/romadebrian/WEB-Sekolah/blob/master/Data%20Base%20school.sql

**Comment by romadebrian** [comment]
kalau masih gak bisa juga impor textnya 1 per 1 aja 
mungkin error karena versi mysqlnya beda
kalau itu saya coba di XAMPP Version 7.4.1

**Comment by irwandi281099** [comment]
cara setting database file koneksi gmana mas di hosting?

**Comment by romadebrian** [comment]
kalau saya sih untuk yang di hosting php 5 begini

`<?PHP
$host="localhost";
$username="xxxxx";
$password="xxxx";
$databasename="school";
$koneksi=mysql_connect($host, $username, $password) or die ("Data base error");
mysql_select_db($databasename, $koneksi);
?>`

**Comment by romadebrian** [comment]
"<?PHP
$host="localhost";
$username="xxxxx";
$password="xxxx";
$databasename="school";
$koneksi=mysql_connect($host, $username, $password) or die ("Data base error");
mysql_select_db($databasename, $koneksi);
?>"

**Comment by romadebrian** [comment]
kalau untuk php 7
![gambar](https://user-images.githubusercontent.com/41140759/79227796-a9f1bc80-7e8a-11ea-8263-aec93f8123c5.png)

**Comment by irwandi281099** [comment]
File cek login.php nya ada yg dirubah gk gan?

**Comment by romadebrian** [comment]
tergantung gan
kodingan saya pakai ini kan untuk php versi 5
kalo pake php versi 7 di ubah :
"mysql_query" menjadi mysqli_query
dan
("SELECT * FROM akun WHERE username='$user'
menjadi
($host, "SELECT * FROM akun WHERE username='$user'

Note : $host itu variable dari file "koneksi.php"

**Comment by irwandi281099** [comment]
Gan tu cara hiden error session_star nya gmana biar gk kliatan errornya di hosting

**Comment by romadebrian** [comment]
tergantung hostingnya gan
kalo saya pakai 000webhost.com jadi cukup ke pengaturan lalu matikan notifikasi error

![gambar](https://user-images.githubusercontent.com/41140759/79477126-05ab7980-8034-11ea-920f-f5dd5c731e51.png)

**Comment by irwandi281099** [comment]
Oke mas nantik saya coba..
Cara bikin export pdf nilai dan data siswa gmana mas?

**Comment by irwandi281099** [comment]
Gan cara input nilai, siswa gimana ya?

**Comment by romadebrian** [comment]
ini kan harusnya error di setiap 
```ruby
session_start();
```
cuma gw tambakan @ jadi 

```ruby
@session_start();
```

jadi errornya gak nampil
padahal error cuma bukan error yang dapat mengganggu system kok wkwkwk
